on:
  push:
    branches: [ main ]
    paths:
    - 'terraform/**'

env:
  
  AWS_REGION : "us-east-1"
 
permissions:
      id-token: write
      contents: read
jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2.0.0
        with:
          role-to-assume: arn:aws:iam::433766115278:role/ghActionsRole
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      - name: setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7
      - name: tf plan
        run: |
          cd terraform
          terraform init
          terraform validate
          terraform plan
      - name: tf apply
        run: | 
          cd terraform
          terraform apply -auto-approve
      - name: run cloudfront invalidation
        run: | 
          cd terraform
          aws cloudfront create-invalidation --distribution-id $(terraform output -raw cloudfront_distribution_id) --paths "/*"
